/home/ICer/IC/Projects/System/rtl/ALU.v
/home/ICer/IC/Projects/System/rtl/ASYNC_FIFO.v
/home/ICer/IC/Projects/System/rtl/Clk_Div.v
/home/ICer/IC/Projects/System/rtl/CLK_GATE.v
/home/ICer/IC/Projects/System/rtl/data_sampling.v
/home/ICer/IC/Projects/System/rtl/DATA_SYNC.v
/home/ICer/IC/Projects/System/rtl/deserializer.v
/home/ICer/IC/Projects/System/rtl/DF_SYNC.v
/home/ICer/IC/Projects/System/rtl/edge_bit_counter.v
/home/ICer/IC/Projects/System/rtl/FIFO_MEM_CNTRL.v
/home/ICer/IC/Projects/System/rtl/FIFO_RD.v
/home/ICer/IC/Projects/System/rtl/FIFO_WR.v
/home/ICer/IC/Projects/System/rtl/FSM_RX.v
/home/ICer/IC/Projects/System/rtl/FSM_TX.sv
/home/ICer/IC/Projects/System/rtl/MUX.v
/home/ICer/IC/Projects/System/rtl/Parity_Calc.v
/home/ICer/IC/Projects/System/rtl/parity_checker.v
/home/ICer/IC/Projects/System/rtl/prescale_mux.v
/home/ICer/IC/Projects/System/rtl/Pulse_Gen.v
/home/ICer/IC/Projects/System/rtl/regfile.v
/home/ICer/IC/Projects/System/rtl/RST_SYNC.v
/home/ICer/IC/Projects/System/rtl/Serializer.v
/home/ICer/IC/Projects/System/rtl/stop_checker.v
/home/ICer/IC/Projects/System/rtl/strt_checker.v
/home/ICer/IC/Projects/System/rtl/SYS_CTRL.v
/home/ICer/IC/Projects/System/rtl/SYSTEM_TOP.v
/home/ICer/IC/Projects/System/rtl/UART.v
/home/ICer/IC/Projects/System/rtl/UART_RX.v
/home/ICer/IC/Projects/System/rtl/UART_TX.v
