## 
## Cadence First Encounter "v08.10-p004_1 ((32bit) 11/04/2008 14:34 (Linux 2.6))"
## Sun Oct  4 23:52:43 2026
## 
set sdc_version 1.4
current_design SYS_TOP
create_clock [get_ports {UART_CLK}]  -name uart_clk -period 271.267 -waveform {0 135.634}
set_clock_transition  -rise -min 0.05 [get_clocks {uart_clk}]
set_clock_transition  -rise -max 0.05 [get_clocks {uart_clk}]
set_clock_transition  -fall -min 0.05 [get_clocks {uart_clk}]
set_clock_transition  -fall -max 0.05 [get_clocks {uart_clk}]
create_clock [get_ports {REF_CLK}]  -name ref_clk -period 10 -waveform {0 5}
set_clock_transition  -rise -min 0.05 [get_clocks {ref_clk}]
set_clock_transition  -rise -max 0.05 [get_clocks {ref_clk}]
set_clock_transition  -fall -min 0.05 [get_clocks {ref_clk}]
set_clock_transition  -fall -max 0.05 [get_clocks {ref_clk}]
create_clock [get_ports {scan_clk}]  -name dft_clk -period 1000 -waveform {0 500}
set_clock_transition  -rise -min 0.05 [get_clocks {dft_clk}]
set_clock_transition  -rise -max 0.05 [get_clocks {dft_clk}]
set_clock_transition  -fall -min 0.05 [get_clocks {dft_clk}]
set_clock_transition  -fall -max 0.05 [get_clocks {dft_clk}]
create_generated_clock -name rx_clk -source [get_ports {UART_CLK}] -divide_by 1 -master_clock [get_clocks {uart_clk}] -add [get_pins {U1_RX_CLK_DIV/U10/Y}]
create_generated_clock -name tx_clk -source [get_ports {UART_CLK}] -divide_by 32 -master_clock [get_clocks {uart_clk}] -add [get_pins {U0_TX_CLK_DIV/U10/Y}]
create_generated_clock -name alu_clk -source [get_ports {REF_CLK}] -divide_by 1 -master_clock [get_clocks {ref_clk}] -add [list [get_pins {U0_CLK_GATE/U0/ECK}] [get_pins {C89/Y}] ]
set_propagated_clock  [get_pins {U1_RX_CLK_DIV/U10/Y}]
set_propagated_clock  [get_ports {UART_CLK}]
set_propagated_clock  [get_pins {U0_TX_CLK_DIV/U10/Y}]
set_propagated_clock  [get_ports {scan_clk}]
set_propagated_clock  [get_ports {REF_CLK}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -min -pin Y -from_pin A [get_ports {test_mode}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -min -pin Y -from_pin A [get_ports {test_mode}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -max -pin Y -from_pin A [get_ports {test_mode}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -max -pin Y -from_pin A [get_ports {test_mode}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -min -pin Y -from_pin A [get_ports {SE}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -min -pin Y -from_pin A [get_ports {SE}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -max -pin Y -from_pin A [get_ports {SE}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -max -pin Y -from_pin A [get_ports {SE}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -min -pin Y -from_pin A [get_ports {SI[3]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -min -pin Y -from_pin A [get_ports {SI[3]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -max -pin Y -from_pin A [get_ports {SI[3]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -max -pin Y -from_pin A [get_ports {SI[3]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -min -pin Y -from_pin A [get_ports {SI[2]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -min -pin Y -from_pin A [get_ports {SI[2]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -max -pin Y -from_pin A [get_ports {SI[2]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -max -pin Y -from_pin A [get_ports {SI[2]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -min -pin Y -from_pin A [get_ports {SI[1]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -min -pin Y -from_pin A [get_ports {SI[1]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -max -pin Y -from_pin A [get_ports {SI[1]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -max -pin Y -from_pin A [get_ports {SI[1]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -min -pin Y -from_pin A [get_ports {SI[0]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -min -pin Y -from_pin A [get_ports {SI[0]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -max -pin Y -from_pin A [get_ports {SI[0]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -max -pin Y -from_pin A [get_ports {SI[0]}]
set_load -pin_load -max  0.1  [get_ports {SO[3]}]
set_load -pin_load -min  0.1  [get_ports {SO[3]}]
set_load -pin_load -max  0.1  [get_ports {SO[2]}]
set_load -pin_load -min  0.1  [get_ports {SO[2]}]
set_load -pin_load -max  0.1  [get_ports {SO[1]}]
set_load -pin_load -min  0.1  [get_ports {SO[1]}]
set_load -pin_load -max  0.1  [get_ports {SO[0]}]
set_load -pin_load -min  0.1  [get_ports {SO[0]}]
set_load -pin_load -max  0.1  [get_ports {parity_error}]
set_load -pin_load -min  0.1  [get_ports {parity_error}]
set_load -pin_load -max  0.1  [get_ports {framing_error}]
set_load -pin_load -min  0.1  [get_ports {framing_error}]
set_case_analysis 1 [get_ports {SE}]
set_case_analysis 1 [get_ports {test_mode}]
set_wire_load_model -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -max -name tsmc13_wl10
set_wire_load_model -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -min -name tsmc13_wl10
set_input_delay -add_delay 200 -clock [get_clocks {dft_clk}] [get_ports {SI[3]}]
set_input_delay -add_delay 200 -clock [get_clocks {dft_clk}] [get_ports {SI[1]}]
set_input_delay -add_delay 200 -clock [get_clocks {dft_clk}] [get_ports {SE}]
set_input_delay -add_delay 200 -clock [get_clocks {dft_clk}] [get_ports {test_mode}]
set_input_delay -add_delay 54.2535 -clock [get_clocks {uart_clk}] [get_ports {UART_RX_IN}]
set_input_delay -add_delay 200 -clock [get_clocks {dft_clk}] [get_ports {SI[2]}]
set_input_delay -add_delay 200 -clock [get_clocks {dft_clk}] [get_ports {SI[0]}]
set_output_delay -add_delay 200 -clock [get_clocks {dft_clk}] [get_ports {SO[1]}]
set_output_delay -add_delay 54.2535 -clock [get_clocks {uart_clk}] [get_ports {parity_error}]
set_output_delay -add_delay 54.2535 -clock [get_clocks {uart_clk}] [get_ports {UART_TX_O}]
set_output_delay -add_delay 200 -clock [get_clocks {dft_clk}] [get_ports {SO[2]}]
set_output_delay -add_delay 54.2535 -clock [get_clocks {uart_clk}] [get_ports {framing_error}]
set_output_delay -add_delay 200 -clock [get_clocks {dft_clk}] [get_ports {SO[0]}]
set_output_delay -add_delay 200 -clock [get_clocks {dft_clk}] [get_ports {SO[3]}]
set_clock_uncertainty 0.1 -hold [get_clocks {dft_clk}]
set_clock_uncertainty 0.2 -setup [get_clocks {dft_clk}]
set_clock_uncertainty 0.1 -hold [get_clocks {ref_clk}]
set_clock_uncertainty 0.2 -setup [get_clocks {ref_clk}]
set_clock_uncertainty 0.1 -hold [get_clocks {uart_clk}]
set_clock_uncertainty 0.2 -setup [get_clocks {uart_clk}]
set_clock_groups -name uart_clk_1 -asynchronous  -group  [get_clocks {tx_clk rx_clk uart_clk}] -group  [get_clocks {alu_clk ref_clk}]
set_clock_groups -name dft_clk_others_1 -logically_exclusive  -group  [get_clocks {dft_clk}]
